version: "3.3"

services:
  app:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
